name: mobile_web_flutter
description: A Flutter web app for AI Plant Health
publish_to: 'none' # khÃ´ng publish lÃªn pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.2.2
  flutter_localizations:
    sdk: flutter
  # GÃ³i cÆ¡ báº£n
  cupertino_icons: ^1.0.8
  go_router: ^14.0.0
  path_provider: ^2.1.0
  open_filex: ^4.0.0
  # Gá»i API backend
  http: ^1.2.2
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  geolocator: ^12.0.0
  shared_preferences: ^2.2.0
  # Chá»n áº£nh (gallery/camera)
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  intl: ^0.19.0   # ðŸ‘ˆ THÃŠM DÃ’NG NÃ€Y
  google_generative_ai: ^0.4.6
  video_player: ^2.8.0
  provider: ^6.1.5+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/zestguard_intro.jpg

